version: '3.7'

services:
  nodejs:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
    container_name: node
    working_dir: /var/www
    depends_on:
      - postgres
    ports:
      - '3333:3333'
    volumes:
      - ./:/var/www
    networks:
      - app-network

  webserver:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - '8000:8000'
    volumes:
      - ./:/var/www
      - ./nginx/:/etc/nginx/conf.d/
    networks:
      - app-network

  postgres:
    image: mdillon/postgis
    container_name: postgresql
    restart: unless-stopped
    environment:
      POSTGRES_DB: graphql_microservices_local
      POSTGRES_USER: pgadmin
      POSTGRES_PASSWORD: password
    tty: true
    ports:
      - '5432:5432'
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./postgresql/postgresql.conf:/etc/postgresql/postgresql.conf
    networks:
      - app-network

  adminer-container:
    image: adminer
    container_name: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
    networks:
      - app-network

#Networks
networks:
  app-network:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local
