version: '3.7'

services:
  nodejs:
    build:
      context: ./.docker
    container_name: node
    command: ['./.docker/run.sh']
    depends_on:
      - postgres
    ports:
      - '3333:3333'
      - '4200:4200'
    volumes:
      - ./:/var/www:delegated
    networks:
      - app-network

  postgres:
    image: mdillon/postgis
    container_name: postgresql
    restart: unless-stopped
    environment:
      POSTGRES_DB: graphql_microservices_local
      POSTGRES_USER: pgadmin
      POSTGRES_PASSWORD: password
    tty: true
    ports:
      - '5432:5432'
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./postgresql/postgresql.conf:/etc/postgresql/postgresql.conf
    networks:
      - app-network

  adminer-container:
    image: adminer
    container_name: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
    networks:
      - app-network

#Networks
networks:
  app-network:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local
